'use strict';

const mongoose = require('mongoose');

// All possible achievements defined here as a reference
const ACHIEVEMENT_DEFINITIONS = [
  {
    slug: 'first-session',
    name: 'First Step',
    desc: 'Log your very first study session',
    icon: 'Play',
    level: 'bronze',
    color: 'text-[#CD7F32]',
    bg: 'bg-[#CD7F32]/15',
  },
  {
    slug: 'first-subject-completed',
    name: 'Subject Mastery Starter',
    desc: 'Complete all chapters in a subject',
    icon: 'BookOpen',
    level: 'bronze',
    color: 'text-[#CD7F32]',
    bg: 'bg-[#CD7F32]/15',
  },
  {
    slug: 'first-chapter-completed',
    name: 'Chapter Closed',
    desc: 'Mark your first syllabus chapter as completed',
    icon: 'CheckSquare',
    level: 'bronze',
    color: 'text-[#CD7F32]',
    bg: 'bg-[#CD7F32]/15',
  },
  {
    slug: '7-day-streak',
    name: 'Weekly Warrior',
    desc: 'Maintain a 7-day study streak (minimum 15 mins daily)',
    icon: 'Zap',
    level: 'silver',
    color: 'text-slate-300',
    bg: 'bg-slate-400/15',
  },
  {
    slug: '30-day-streak',
    name: 'Monthly Monolith',
    desc: 'Maintain a 30-day study streak (minimum 15 mins daily)',
    icon: 'Flame',
    level: 'gold',
    color: 'text-[#FFD700]',
    bg: 'bg-[#FFD700]/15',
  },
  {
    slug: '100-hours-studied',
    name: 'Century Scholar',
    desc: 'Accumulate 100 hours of study time',
    icon: 'Clock',
    level: 'silver',
    color: 'text-slate-300',
    bg: 'bg-slate-400/15',
  },
  {
    slug: '250-hours-studied',
    name: 'Elite Academic',
    desc: 'Accumulate 250 hours of study time',
    icon: 'Award',
    level: 'gold',
    color: 'text-[#FFD700]',
    bg: 'bg-[#FFD700]/15',
  },
  {
    slug: '500-hours-studied',
    name: 'Ultimate Sage',
    desc: 'Accumulate 500 hours of study time',
    icon: 'Trophy',
    level: 'diamond',
    color: 'text-[#B9F2FF]',
    bg: 'bg-[#B9F2FF]/15',
  },
  {
    slug: 'completed-semester',
    name: 'Semester Conqueror',
    desc: 'Complete 100% of your active semester chapters',
    icon: 'GraduationCap',
    level: 'gold',
    color: 'text-[#FFD700]',
    bg: 'bg-[#FFD700]/15',
  },
  {
    slug: 'ai-planner-follower',
    name: 'AI Companion',
    desc: 'Log a study session generated by the AI Study Planner',
    icon: 'Compass',
    level: 'silver',
    color: 'text-slate-300',
    bg: 'bg-slate-400/15',
  },
];

const achievementSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    slug: {
      type: String,
      required: true,
      enum: ACHIEVEMENT_DEFINITIONS.map((a) => a.slug),
    },
    notified: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  }
);

// Each user can earn each achievement only once
achievementSchema.index({ userId: 1, slug: 1 }, { unique: true });

const Achievement = mongoose.model('Achievement', achievementSchema);

module.exports = Achievement;
module.exports.ACHIEVEMENT_DEFINITIONS = ACHIEVEMENT_DEFINITIONS;

